fix(deps): update dependency org.springframework.boot:spring-boot-dependencies to v4.0.1 (#943)
This PR contains the following updates:

| Package | Change |
[Age](https://docs.renovatebot.com/merge-confidence/) |
[Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
|
[org.springframework.boot:spring-boot-dependencies](https://spring.io/projects/spring-boot)
([source](https://redirect.github.com/spring-projects/spring-boot)) |
`4.0.0` → `4.0.1` |
![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-dependencies/4.0.1?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-dependencies/4.0.0/4.0.1?slim=true)
|

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>spring-projects/spring-boot
(org.springframework.boot:spring-boot-dependencies)</summary>

###
[`v4.0.1`](https://redirect.github.com/spring-projects/spring-boot/releases/tag/v4.0.1)

[Compare
Source](https://redirect.github.com/spring-projects/spring-boot/compare/v4.0.0...v4.0.1)

#### :warning: Noteworthy Changes

- Hibernate has been upgraded to 7.2.0.Final in response to Hibernate
7.1 moving to limited support
- spring-boot-starter-kotlin-serialization has been renamed to to
spring-boot-starter-kotlinx-serialization-json and
spring-boot-starter-kotlin-serialization-test has been renamed to
spring-boot-starter-kotlinx-serialization-json-test. This change aligns
the starters' names with those of their respective modules
- Using TestRestTemplate now [requires a dependency on
spring-boot-restclient](https://docs.spring.io/spring-boot/4.0-SNAPSHOT/reference/testing/spring-boot-applications.html#testing.spring-boot-applications.with-running-server)

#### :lady\_beetle: Bug Fixes

- JsonMixinModuleEntriesBeanRegistrationAotProcessor does not handle
deprecated code
[#&#8203;48564](https://redirect.github.com/spring-projects/spring-boot/issues/48564)
- JdbcSessionAutoConfiguration may not match when using the
auto-configured DataSource
[#&#8203;48552](https://redirect.github.com/spring-projects/spring-boot/pull/48552)
- `@ServiceConnection` for LgtmStackContainer fails when logging
endpoint is configured due to multiple OtlpLoggingConnectionDetails
beans
[#&#8203;48536](https://redirect.github.com/spring-projects/spring-boot/issues/48536)
- WebApplicationType does not consider modules when deduced from
classpath
[#&#8203;48517](https://redirect.github.com/spring-projects/spring-boot/issues/48517)
- Spring Session auto-configuration fails in a war deployment as
ServerProperties is not available
[#&#8203;48493](https://redirect.github.com/spring-projects/spring-boot/issues/48493)
- Opentelemetry logging export requires actuator module
[#&#8203;48488](https://redirect.github.com/spring-projects/spring-boot/issues/48488)
- RabbitHealthIndicator reports an error when version is missing from
the connection's server properties
[#&#8203;48487](https://redirect.github.com/spring-projects/spring-boot/issues/48487)
- Actuator Info class has inconsistent nullability annotations and
cannot be built with null value
[#&#8203;48480](https://redirect.github.com/spring-projects/spring-boot/pull/48480)
- Profiles retained during AOT processing are not configured in a native
image
[#&#8203;48476](https://redirect.github.com/spring-projects/spring-boot/issues/48476)
- Security matchers and WebServerNamespace resolution can fail with
NoClassDefFoundError when used in a traditional WAR deployment
[#&#8203;48388](https://redirect.github.com/spring-projects/spring-boot/issues/48388)
- HealthEndpointGroupMembershipValidator does not consider reactive
health indicators causing NoSuchHealthContributorException to be thrown
[#&#8203;48387](https://redirect.github.com/spring-projects/spring-boot/issues/48387)
- spring.jackson.default-property-inclusion is not applied to content
inclusion
[#&#8203;48343](https://redirect.github.com/spring-projects/spring-boot/issues/48343)
- TestRestTemplate.getRootUri() returns empty string
[#&#8203;48330](https://redirect.github.com/spring-projects/spring-boot/issues/48330)
- Redis health check reports an error when redis\_version is missing
from the INFO response
[#&#8203;48328](https://redirect.github.com/spring-projects/spring-boot/issues/48328)
- Parent's MeterRegistry beans are closed when child context closes
[#&#8203;48325](https://redirect.github.com/spring-projects/spring-boot/issues/48325)
- HttpMessageConverters picks up converter beans for both client and
server
[#&#8203;48310](https://redirect.github.com/spring-projects/spring-boot/issues/48310)
- Conditions to auto-configure a RestClient are outdated with the
modularization
[#&#8203;48308](https://redirect.github.com/spring-projects/spring-boot/issues/48308)
- A custom JwtTypeValidator that replaces the default can no longer be
configured
[#&#8203;48301](https://redirect.github.com/spring-projects/spring-boot/issues/48301)
- PropertiesRestClientHttpServiceGroupConfigurer has highest precedence,
preventing other configurers from being ordered ahead of it
[#&#8203;48296](https://redirect.github.com/spring-projects/spring-boot/issues/48296)
- SpringBootTest.UseMainMethod.WHEN\_AVAILABLE and ALWAYS are
incompatible with package-private or parameter-less main method
[#&#8203;48275](https://redirect.github.com/spring-projects/spring-boot/issues/48275)
- Conditions to auto-configure RestClient-based HTTP service clients are
outdated with the modularization
[#&#8203;48274](https://redirect.github.com/spring-projects/spring-boot/pull/48274)
- Starter for Kotlinx Serialization Json is misnamed
[#&#8203;48262](https://redirect.github.com/spring-projects/spring-boot/issues/48262)
- ApplicationServletEnvironment is no longer configured in war
deployments
[#&#8203;48254](https://redirect.github.com/spring-projects/spring-boot/issues/48254)
- RestClient.Builder bean present in `@SpringBootTest` due to
spring-boot-starter-webmvc-test, but missing at runtime without
restclient starter
[#&#8203;48253](https://redirect.github.com/spring-projects/spring-boot/issues/48253)
- ProblemDetail is rendered to XML incorrectly
[#&#8203;48222](https://redirect.github.com/spring-projects/spring-boot/pull/48222)

#### :notebook\_with\_decorative\_cover: Documentation

- Harmonize Kotlin example for HTTP Service client support
[#&#8203;48577](https://redirect.github.com/spring-projects/spring-boot/pull/48577)
- Document HttpMessageConverters detection changes in 4.0.1
[#&#8203;48574](https://redirect.github.com/spring-projects/spring-boot/issues/48574)
- Improve javadoc for when to use class names rather than class
references
[#&#8203;48569](https://redirect.github.com/spring-projects/spring-boot/issues/48569)
- Documentation has an outdated reference to the Jackson Kotlin Module
[#&#8203;48534](https://redirect.github.com/spring-projects/spring-boot/issues/48534)
- Caching documentation should clarify how to use a no-op implementation
to run a test suite
[#&#8203;48532](https://redirect.github.com/spring-projects/spring-boot/issues/48532)
- Document that the default rolling policy for Log4j2 requires
logging.file.path to be set
[#&#8203;48527](https://redirect.github.com/spring-projects/spring-boot/issues/48527)
- Review documentation and migration guide about changes in
`@AutoConfigureCache`
[#&#8203;48522](https://redirect.github.com/spring-projects/spring-boot/issues/48522)
- License header in build samples is displayed in the reference
documentation
[#&#8203;48478](https://redirect.github.com/spring-projects/spring-boot/issues/48478)
- Configuring Two DataSources How-To code sample is inconsistent
[#&#8203;48449](https://redirect.github.com/spring-projects/spring-boot/issues/48449)
- Fix links to source files on GitHub
[#&#8203;48398](https://redirect.github.com/spring-projects/spring-boot/pull/48398)
- Documentation contains broken links to GitHub source files
[#&#8203;48394](https://redirect.github.com/spring-projects/spring-boot/issues/48394)
- Document that org.aspectj.weaver.Advice must be on the classpath to
enable support for Micrometer's annotations
[#&#8203;48360](https://redirect.github.com/spring-projects/spring-boot/issues/48360)
- Correct the annotation in the Kotlin `@ConfigurationPropertiesSource`
example
[#&#8203;48357](https://redirect.github.com/spring-projects/spring-boot/pull/48357)
- Polish TestRestTemplate examples in the reference guide
[#&#8203;48336](https://redirect.github.com/spring-projects/spring-boot/issues/48336)
- Documentation missing for LocalTestWebServer
[#&#8203;48333](https://redirect.github.com/spring-projects/spring-boot/issues/48333)
- Update "Creating Your Own Starter" following modularisation
[#&#8203;48317](https://redirect.github.com/spring-projects/spring-boot/issues/48317)
- Fix links to javadoc in the reference documentation
[#&#8203;48300](https://redirect.github.com/spring-projects/spring-boot/issues/48300)
- Update references for RestTemplateCustomizer and RestTemplateBuilder
classes in documentation
[#&#8203;48295](https://redirect.github.com/spring-projects/spring-boot/pull/48295)
- Remove modules section of the README following modularisation
[#&#8203;48291](https://redirect.github.com/spring-projects/spring-boot/issues/48291)
- Wrong number in Graceful Shutdown chapter
[#&#8203;48284](https://redirect.github.com/spring-projects/spring-boot/issues/48284)
- Mention new spring-boot-h2console module when describing how to use H2
Console
[#&#8203;48278](https://redirect.github.com/spring-projects/spring-boot/pull/48278)
- Clarify that `@EnableBatchProcessing` turns off all batch
auto-configuration, including schema initialization
[#&#8203;48266](https://redirect.github.com/spring-projects/spring-boot/issues/48266)
- Documented replacements for spring.jackson.generator and
spring.jackson.parser are inverted
[#&#8203;48255](https://redirect.github.com/spring-projects/spring-boot/pull/48255)
- Document the need for a JdbcDialect bean when using Spring Data JDBC
and AOT
[#&#8203;48240](https://redirect.github.com/spring-projects/spring-boot/issues/48240)
- Update reference documentation as Spring Batch's resourceless
infrastructure means that it no longer always requires a DataSource
[#&#8203;48233](https://redirect.github.com/spring-projects/spring-boot/issues/48233)
- Kotlin auto-configuration examples are not annotated with
`@AutoConfiguration`
[#&#8203;48228](https://redirect.github.com/spring-projects/spring-boot/issues/48228)
- Revise "Use Liquibase for test-only migrations" section in reference
manual
[#&#8203;48219](https://redirect.github.com/spring-projects/spring-boot/issues/48219)
- Infinispan Cache Documentation is outdated
[#&#8203;48218](https://redirect.github.com/spring-projects/spring-boot/issues/48218)
- Removed max-attempts properties metadata don't have replacement
[#&#8203;48206](https://redirect.github.com/spring-projects/spring-boot/issues/48206)
- Polish documentation on testing web applications and the various
testing clients that are available
[#&#8203;47948](https://redirect.github.com/spring-projects/spring-boot/issues/47948)

#### :hammer: Dependency Upgrades

- Upgrade to AspectJ 1.9.25.1
[#&#8203;48561](https://redirect.github.com/spring-projects/spring-boot/issues/48561)
- Upgrade to Elasticsearch Client 9.2.2
[#&#8203;48447](https://redirect.github.com/spring-projects/spring-boot/issues/48447)
- Upgrade to Groovy 5.0.3
[#&#8203;48460](https://redirect.github.com/spring-projects/spring-boot/issues/48460)
- Upgrade to Hibernate 7.2.0.Final
[#&#8203;48518](https://redirect.github.com/spring-projects/spring-boot/issues/48518)
- Upgrade to Jackson Bom 3.0.3
[#&#8203;48462](https://redirect.github.com/spring-projects/spring-boot/issues/48462)
- Upgrade to Jetty 12.1.5
[#&#8203;48463](https://redirect.github.com/spring-projects/spring-boot/issues/48463)
- Upgrade to jOOQ 3.19.29
[#&#8203;48464](https://redirect.github.com/spring-projects/spring-boot/issues/48464)
- Upgrade to Json Path 2.10.0
[#&#8203;48553](https://redirect.github.com/spring-projects/spring-boot/issues/48553)
- Upgrade to Log4j2 2.25.3
[#&#8203;48551](https://redirect.github.com/spring-projects/spring-boot/issues/48551)
- Upgrade to MariaDB 3.5.7
[#&#8203;48562](https://redirect.github.com/spring-projects/spring-boot/issues/48562)
- Upgrade to Micrometer 1.16.1
[#&#8203;48433](https://redirect.github.com/spring-projects/spring-boot/issues/48433)
- Upgrade to Micrometer Tracing 1.6.1
[#&#8203;48434](https://redirect.github.com/spring-projects/spring-boot/issues/48434)
- Upgrade to MongoDB 5.6.2
[#&#8203;48501](https://redirect.github.com/spring-projects/spring-boot/issues/48501)
- Upgrade to Netty 4.2.9.Final
[#&#8203;48544](https://redirect.github.com/spring-projects/spring-boot/issues/48544)
- Upgrade to Pooled JMS 3.1.8
[#&#8203;48563](https://redirect.github.com/spring-projects/spring-boot/issues/48563)
- Upgrade to Pulsar 4.1.2
[#&#8203;48465](https://redirect.github.com/spring-projects/spring-boot/issues/48465)
- Upgrade to Quartz 2.5.2
[#&#8203;48466](https://redirect.github.com/spring-projects/spring-boot/issues/48466)
- Upgrade to Reactor Bom 2025.0.1
[#&#8203;48435](https://redirect.github.com/spring-projects/spring-boot/issues/48435)
- Upgrade to Spring AMQP 4.0.1
[#&#8203;48436](https://redirect.github.com/spring-projects/spring-boot/issues/48436)
- Upgrade to Spring Batch 6.0.1
[#&#8203;48437](https://redirect.github.com/spring-projects/spring-boot/issues/48437)
- Upgrade to Spring Data Bom 2025.1.1
[#&#8203;48438](https://redirect.github.com/spring-projects/spring-boot/issues/48438)
- Upgrade to Spring Framework 7.0.2
[#&#8203;48439](https://redirect.github.com/spring-projects/spring-boot/issues/48439)
- Upgrade to Spring GraphQL 2.0.1
[#&#8203;48440](https://redirect.github.com/spring-projects/spring-boot/issues/48440)
- Upgrade to Spring HATEOAS 3.0.1
[#&#8203;48481](https://redirect.github.com/spring-projects/spring-boot/issues/48481)
- Upgrade to Spring Integration 7.0.1
[#&#8203;48482](https://redirect.github.com/spring-projects/spring-boot/issues/48482)
- Upgrade to Spring Kafka 4.0.1
[#&#8203;48441](https://redirect.github.com/spring-projects/spring-boot/issues/48441)
- Upgrade to Spring LDAP 4.0.1
[#&#8203;48442](https://redirect.github.com/spring-projects/spring-boot/issues/48442)
- Upgrade to Spring Pulsar 2.0.1
[#&#8203;48443](https://redirect.github.com/spring-projects/spring-boot/issues/48443)
- Upgrade to Spring Security 7.0.2
[#&#8203;48444](https://redirect.github.com/spring-projects/spring-boot/issues/48444)
- Upgrade to Spring Session 4.0.1
[#&#8203;48445](https://redirect.github.com/spring-projects/spring-boot/issues/48445)
- Upgrade to Testcontainers 2.0.3
[#&#8203;48545](https://redirect.github.com/spring-projects/spring-boot/issues/48545)
- Upgrade to Tomcat 11.0.15
[#&#8203;48467](https://redirect.github.com/spring-projects/spring-boot/issues/48467)
- Upgrade to UnboundID LDAPSDK 7.0.4
[#&#8203;48468](https://redirect.github.com/spring-projects/spring-boot/issues/48468)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;Nhahan](https://redirect.github.com/Nhahan),
[@&#8203;arey](https://redirect.github.com/arey),
[@&#8203;banseok1216](https://redirect.github.com/banseok1216),
[@&#8203;berry120](https://redirect.github.com/berry120),
[@&#8203;candrews](https://redirect.github.com/candrews),
[@&#8203;dmitrysulman](https://redirect.github.com/dmitrysulman),
[@&#8203;geopark021](https://redirect.github.com/geopark021),
[@&#8203;hktechn0](https://redirect.github.com/hktechn0),
[@&#8203;igslznev](https://redirect.github.com/igslznev),
[@&#8203;jwalter](https://redirect.github.com/jwalter),
[@&#8203;kzander91](https://redirect.github.com/kzander91),
[@&#8203;michaldo](https://redirect.github.com/michaldo),
[@&#8203;mzeijen](https://redirect.github.com/mzeijen),
[@&#8203;ngocnhan-tran1996](https://redirect.github.com/ngocnhan-tran1996),
[@&#8203;noojung](https://redirect.github.com/noojung),
[@&#8203;scottfrederick](https://redirect.github.com/scottfrederick),
[@&#8203;vpavic](https://redirect.github.com/vpavic), and
[@&#8203;youngledo](https://redirect.github.com/youngledo)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

## Need help?
You can ask for more help in the following Slack channel:
#proj-renovate-self-hosted. In that channel you can also find ADR and
FAQ docs in the Resources section.

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0Mi42NC4xIiwidXBkYXRlZEluVmVyIjoiNDIuNjQuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsidXBkYXRlLXBhdGNoIl19-->

Signed-off-by: renovate-sh-app[bot] <219655108+renovate-sh-app[bot]@users.noreply.github.com>
Co-authored-by: renovate-sh-app[bot] <219655108+renovate-sh-app[bot]@users.noreply.github.com>