fix(deps): update dependency org.springframework.boot:spring-boot-dependencies to v3.4.2 (#258)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
|
[org.springframework.boot:spring-boot-dependencies](https://spring.io/projects/spring-boot)
([source](https://redirect.github.com/spring-projects/spring-boot)) |
import | patch | `3.4.1` -> `3.4.2` |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the warning logs for
more information.

---

### Release Notes

<details>
<summary>spring-projects/spring-boot
(org.springframework.boot:spring-boot-dependencies)</summary>

###
[`v3.4.2`](https://redirect.github.com/spring-projects/spring-boot/releases/tag/v3.4.2)

[Compare
Source](https://redirect.github.com/spring-projects/spring-boot/compare/v3.4.1...v3.4.2)

#### :lady_beetle: Bug Fixes

- Property metadata for "logging.structured.json.customizer" has
incorrect type
[#&#8203;43916](https://redirect.github.com/spring-projects/spring-boot/issues/43916)
- GraylogExtendedLogFormatProperties throws NullPointerException when
only 'logging.structured.gelf.host' is specified
[#&#8203;43863](https://redirect.github.com/spring-projects/spring-boot/pull/43863)
- Structured logging properties have no effect in a native image
[#&#8203;43862](https://redirect.github.com/spring-projects/spring-boot/pull/43862)
- Docker Compose support for ClickHouse does not allow an empty password
when ALLOW_EMPTY_PASSWORD=yes
[#&#8203;43790](https://redirect.github.com/spring-projects/spring-boot/pull/43790)
- docker compose ps now fails due to unknown --orphans flag with 2.23 or
earlier
[#&#8203;43717](https://redirect.github.com/spring-projects/spring-boot/issues/43717)
- Build info timestamp is truncated to seconds
[#&#8203;43617](https://redirect.github.com/spring-projects/spring-boot/issues/43617)
- FileWatcher used for SSL reload does not support symlinks
[#&#8203;43604](https://redirect.github.com/spring-projects/spring-boot/issues/43604)
- BindableRuntimeHintsRegistrar should handle TypeNotPresentException
[#&#8203;43600](https://redirect.github.com/spring-projects/spring-boot/issues/43600)
- CapturedOutput is empty when using Log4J2 StatusLogger
[#&#8203;43578](https://redirect.github.com/spring-projects/spring-boot/issues/43578)
- Spring Boot 3.4 is not compatible with Gson 2.10
[#&#8203;43442](https://redirect.github.com/spring-projects/spring-boot/issues/43442)
- NoClassDefFoundError when using JUnit to test a Gradle 7.6.x app that
depends on spring-boot-actuator-autoconfigure but not on
org.junit.platform:junit-platform-launcher
[#&#8203;43340](https://redirect.github.com/spring-projects/spring-boot/issues/43340)

#### :notebook_with_decorative_cover: Documentation

- Document that the `@ConfigurationProperties` annotation processor
cannot generate description and defaultValue metadata for external types
[#&#8203;43929](https://redirect.github.com/spring-projects/spring-boot/issues/43929)
- Fix description of management.metrics.graphql.autotime.enabled
[#&#8203;43905](https://redirect.github.com/spring-projects/spring-boot/issues/43905)
- Document 'base64:' prefix support
[#&#8203;43835](https://redirect.github.com/spring-projects/spring-boot/issues/43835)
- Document handling of `@Fallback` beans in
ConditionalOnSingleCandidate's javadoc
[#&#8203;43826](https://redirect.github.com/spring-projects/spring-boot/pull/43826)
- Javadoc of DataSourceBuilder does not reference all supported types
[#&#8203;43732](https://redirect.github.com/spring-projects/spring-boot/issues/43732)
- Update OpenTelemetry section in Supported Monitoring Systems to refer
to OTLP instead
[#&#8203;43729](https://redirect.github.com/spring-projects/spring-boot/issues/43729)
- Consistently document the minimum supported versions of Gradle
[#&#8203;43725](https://redirect.github.com/spring-projects/spring-boot/issues/43725)
- Document that system libraries are a reason to customize the builder
and switch away from builder-jammy-java-tiny
[#&#8203;43716](https://redirect.github.com/spring-projects/spring-boot/issues/43716)
- Links to the Javadoc of Jakarta Messaging are invalid
[#&#8203;43662](https://redirect.github.com/spring-projects/spring-boot/issues/43662)
- Paragraph HTML tags are rendered as-is in Maven Plugin reference
documentation
[#&#8203;43623](https://redirect.github.com/spring-projects/spring-boot/issues/43623)
- Javadoc link for jakarta.xml.bind is invalid
[#&#8203;43607](https://redirect.github.com/spring-projects/spring-boot/issues/43607)
- Documentation still has references to 'layertools'
[#&#8203;43605](https://redirect.github.com/spring-projects/spring-boot/issues/43605)
- Javadoc of ConstructorBinding should not use markdown formatting
[#&#8203;43599](https://redirect.github.com/spring-projects/spring-boot/issues/43599)
- Managed Dependency Coordinates lists Spock and OkHttp dependencies
that are not managed
[#&#8203;43584](https://redirect.github.com/spring-projects/spring-boot/issues/43584)

#### :hammer: Dependency Upgrades

- Upgrade to ActiveMQ 6.1.5
[#&#8203;43791](https://redirect.github.com/spring-projects/spring-boot/issues/43791)
- Upgrade to Commons Codec 1.17.2
[#&#8203;43720](https://redirect.github.com/spring-projects/spring-boot/issues/43720)
- Upgrade to Couchbase Client 3.7.7
[#&#8203;43843](https://redirect.github.com/spring-projects/spring-boot/issues/43843)
- Upgrade to FreeMarker 2.3.34
[#&#8203;43721](https://redirect.github.com/spring-projects/spring-boot/issues/43721)
- Upgrade to Hibernate 6.6.5.Final
[#&#8203;43910](https://redirect.github.com/spring-projects/spring-boot/issues/43910)
- Upgrade to HttpCore5 5.3.2
[#&#8203;43792](https://redirect.github.com/spring-projects/spring-boot/issues/43792)
- Upgrade to Infinispan 15.0.12.Final
[#&#8203;43911](https://redirect.github.com/spring-projects/spring-boot/issues/43911)
- Upgrade to Jersey 3.1.10
[#&#8203;43793](https://redirect.github.com/spring-projects/spring-boot/issues/43793)
- Upgrade to jOOQ 3.19.18
[#&#8203;43844](https://redirect.github.com/spring-projects/spring-boot/issues/43844)
- Upgrade to Lettuce 6.4.2.RELEASE
[#&#8203;43609](https://redirect.github.com/spring-projects/spring-boot/issues/43609)
- Upgrade to Logback 1.5.16
[#&#8203;43715](https://redirect.github.com/spring-projects/spring-boot/issues/43715)
- Upgrade to Micrometer 1.14.3
[#&#8203;43745](https://redirect.github.com/spring-projects/spring-boot/issues/43745)
- Upgrade to Micrometer Tracing 1.4.2
[#&#8203;43746](https://redirect.github.com/spring-projects/spring-boot/issues/43746)
- Upgrade to Netty 4.1.117.Final
[#&#8203;43845](https://redirect.github.com/spring-projects/spring-boot/issues/43845)
- Upgrade to Postgresql 42.7.5
[#&#8203;43846](https://redirect.github.com/spring-projects/spring-boot/issues/43846)
- Upgrade to Pulsar 3.3.4
[#&#8203;43912](https://redirect.github.com/spring-projects/spring-boot/issues/43912)
- Upgrade to R2DBC MySQL 1.3.1
[#&#8203;43722](https://redirect.github.com/spring-projects/spring-boot/issues/43722)
- Upgrade to Reactor Bom 2024.0.2
[#&#8203;43747](https://redirect.github.com/spring-projects/spring-boot/issues/43747)
- Upgrade to Spring AMQP 3.2.2
[#&#8203;43748](https://redirect.github.com/spring-projects/spring-boot/issues/43748)
- Upgrade to Spring Data Bom 2024.1.2
[#&#8203;43749](https://redirect.github.com/spring-projects/spring-boot/issues/43749)
- Upgrade to Spring Framework 6.2.2
[#&#8203;43750](https://redirect.github.com/spring-projects/spring-boot/issues/43750)
- Upgrade to Spring Kafka 3.3.2
[#&#8203;43751](https://redirect.github.com/spring-projects/spring-boot/issues/43751)
- Upgrade to Spring Pulsar 1.2.2
[#&#8203;43752](https://redirect.github.com/spring-projects/spring-boot/issues/43752)
- Upgrade to SQLite JDBC 3.47.2.0
[#&#8203;43723](https://redirect.github.com/spring-projects/spring-boot/issues/43723)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;arefbehboudi](https://redirect.github.com/arefbehboudi),
[@&#8203;dreis2211](https://redirect.github.com/dreis2211),
[@&#8203;gavarava](https://redirect.github.com/gavarava),
[@&#8203;hezean](https://redirect.github.com/hezean),
[@&#8203;izeye](https://redirect.github.com/izeye),
[@&#8203;jxblum](https://redirect.github.com/jxblum),
[@&#8203;ngocnhan-tran1996](https://redirect.github.com/ngocnhan-tran1996),
[@&#8203;nosan](https://redirect.github.com/nosan),
[@&#8203;quaff](https://redirect.github.com/quaff), and
[@&#8203;tmaciejewski](https://redirect.github.com/tmaciejewski)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMTcuMiIsInVwZGF0ZWRJblZlciI6IjM5LjExNy4yIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: grafanarenovatebot[bot] <146220760+grafanarenovatebot[bot]@users.noreply.github.com>